//
//  TestDNSError.swift
//  SwiftDNS
//
//  Created by mtzfederico on 2025-08-20
// 

import Testing
@testable import SwiftDNS

struct TestDNSError {

    @Test func testDNSError_Equatable() async throws {
        #expect(DNSError.invalidData("") == DNSError.invalidData(""))
        #expect(DNSError.invalidData("") != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.invalidData("") != DNSError.unknownState(nil))
        #expect(DNSError.invalidData("") != DNSError.unknownState(.preparing))
        #expect(DNSError.invalidData("") != DNSError.noDataReceived)
        #expect(DNSError.invalidData("") != DNSError.IDMismatch)
        #expect(DNSError.invalidData("") != DNSError.invalidDomainName)
        #expect(DNSError.invalidData("") != DNSError.connectionIsNil)
        #expect(DNSError.invalidData("") != DNSError.invalidServerAddress)
        #expect(DNSError.invalidData("") != DNSError.connectionFailed(DNSError.connectionIsNil))
        #expect(DNSError.invalidData("") != DNSError.parsingError(nil))
        #expect(DNSError.invalidData("") != DNSError.parsingError(DNSError.noDataReceived))
        
        #expect(DNSError.connectionIsNil != DNSError.invalidData(""))
        #expect(DNSError.connectionIsNil != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.connectionIsNil != DNSError.unknownState(nil))
        #expect(DNSError.connectionIsNil != DNSError.unknownState(.preparing))
        #expect(DNSError.connectionIsNil != DNSError.invalidServerAddress)
        #expect(DNSError.connectionIsNil != DNSError.noDataReceived)
        #expect(DNSError.connectionIsNil != DNSError.IDMismatch)
        #expect(DNSError.connectionIsNil != DNSError.invalidDomainName)
        #expect(DNSError.connectionIsNil == DNSError.connectionIsNil)
        #expect(DNSError.connectionIsNil != DNSError.invalidServerAddress)
        #expect(DNSError.connectionIsNil != DNSError.connectionFailed(DNSError.invalidData("Out of bounds")))
        #expect(DNSError.connectionIsNil != DNSError.parsingError(nil))
        #expect(DNSError.connectionIsNil != DNSError.parsingError(DNSError.noDataReceived))
        
        #expect(DNSError.invalidServerAddress != DNSError.invalidData(""))
        #expect(DNSError.invalidServerAddress != DNSError.unknownState(nil))
        #expect(DNSError.invalidServerAddress != DNSError.unknownState(.preparing))
        #expect(DNSError.invalidServerAddress != DNSError.noDataReceived)
        #expect(DNSError.invalidServerAddress != DNSError.noDataReceived)
        #expect(DNSError.invalidServerAddress != DNSError.IDMismatch)
        #expect(DNSError.invalidServerAddress != DNSError.invalidDomainName)
        #expect(DNSError.invalidServerAddress != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.invalidServerAddress != DNSError.connectionIsNil)
        #expect(DNSError.invalidServerAddress == DNSError.invalidServerAddress)
        #expect(DNSError.invalidServerAddress != DNSError.connectionFailed(DNSError.noDataReceived))
        #expect(DNSError.invalidServerAddress != DNSError.parsingError(nil))
        #expect(DNSError.invalidServerAddress != DNSError.parsingError(DNSError.noDataReceived))
        
        #expect(DNSError.parsingError(nil) != DNSError.invalidData(""))
        #expect(DNSError.parsingError(nil) != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.parsingError(nil) != DNSError.unknownState(nil))
        #expect(DNSError.parsingError(nil) != DNSError.unknownState(.preparing))
        #expect(DNSError.parsingError(DNSError.invalidData("")) != DNSError.unknownState(.preparing))
        #expect(DNSError.parsingError(nil) != DNSError.invalidServerAddress)
        #expect(DNSError.parsingError(nil) != DNSError.noDataReceived)
        #expect(DNSError.parsingError(nil) != DNSError.IDMismatch)
        #expect(DNSError.parsingError(nil) != DNSError.invalidDomainName)
        #expect(DNSError.parsingError(nil) != DNSError.connectionIsNil)
        #expect(DNSError.parsingError(nil) != DNSError.invalidServerAddress)
        #expect(DNSError.parsingError(nil) != DNSError.connectionFailed(DNSError.connectionIsNil))
        #expect(DNSError.parsingError(nil) == DNSError.parsingError(nil))
        #expect(DNSError.parsingError(DNSError.noDataReceived) == DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.parsingError(nil) != DNSError.parsingError(DNSError.noDataReceived))
        
        #expect(DNSError.unknownState(nil) != DNSError.invalidData(""))
        #expect(DNSError.unknownState(nil) != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.unknownState(nil) == DNSError.unknownState(nil))
        #expect(DNSError.unknownState(.preparing) == DNSError.unknownState(.preparing))
        #expect(DNSError.unknownState(nil) != DNSError.invalidServerAddress)
        #expect(DNSError.unknownState(nil) != DNSError.noDataReceived)
        #expect(DNSError.unknownState(nil) != DNSError.IDMismatch)
        #expect(DNSError.unknownState(nil) != DNSError.invalidDomainName)
        #expect(DNSError.unknownState(nil) != DNSError.connectionIsNil)
        #expect(DNSError.unknownState(nil) != DNSError.invalidServerAddress)
        #expect(DNSError.unknownState(nil) != DNSError.connectionFailed(DNSError.connectionIsNil))
        #expect(DNSError.unknownState(nil) != DNSError.parsingError(nil))
        #expect(DNSError.unknownState(nil) != DNSError.parsingError(DNSError.noDataReceived))
        
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.invalidData(""))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.connectionFailed(DNSError.invalidData("Out of bounds")))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.unknownState(nil))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.unknownState(.preparing))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.noDataReceived)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.IDMismatch)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.invalidDomainName)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.connectionIsNil)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.invalidServerAddress)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) == DNSError.connectionFailed(DNSError.noDataReceived))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.parsingError(nil))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.parsingError(DNSError.noDataReceived))
        
        #expect(DNSError.noDataReceived != DNSError.invalidData(""))
        #expect(DNSError.noDataReceived != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.noDataReceived != DNSError.unknownState(nil))
        #expect(DNSError.noDataReceived != DNSError.unknownState(.preparing))
        #expect(DNSError.noDataReceived == DNSError.noDataReceived)
        #expect(DNSError.noDataReceived != DNSError.IDMismatch)
        #expect(DNSError.noDataReceived != DNSError.invalidDomainName)
        #expect(DNSError.noDataReceived != DNSError.connectionIsNil)
        #expect(DNSError.noDataReceived != DNSError.invalidServerAddress)
        #expect(DNSError.noDataReceived != DNSError.parsingError(nil))
        #expect(DNSError.noDataReceived != DNSError.parsingError(DNSError.noDataReceived))
        
        #expect(DNSError.IDMismatch != DNSError.invalidData(""))
        #expect(DNSError.IDMismatch != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.IDMismatch != DNSError.unknownState(nil))
        #expect(DNSError.IDMismatch != DNSError.unknownState(.preparing))
        #expect(DNSError.IDMismatch != DNSError.noDataReceived)
        #expect(DNSError.IDMismatch == DNSError.IDMismatch)
        #expect(DNSError.IDMismatch != DNSError.invalidDomainName)
        #expect(DNSError.IDMismatch != DNSError.connectionIsNil)
        #expect(DNSError.IDMismatch != DNSError.invalidServerAddress)
        #expect(DNSError.IDMismatch != DNSError.parsingError(nil))
        #expect(DNSError.IDMismatch != DNSError.parsingError(DNSError.noDataReceived))
        
        #expect(DNSError.invalidDomainName != DNSError.invalidData(""))
        #expect(DNSError.invalidDomainName != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.invalidDomainName != DNSError.unknownState(nil))
        #expect(DNSError.invalidDomainName != DNSError.unknownState(.preparing))
        #expect(DNSError.invalidDomainName != DNSError.noDataReceived)
        #expect(DNSError.invalidDomainName != DNSError.IDMismatch)
        #expect(DNSError.invalidDomainName == DNSError.invalidDomainName)
        #expect(DNSError.invalidDomainName != DNSError.connectionIsNil)
        #expect(DNSError.invalidDomainName != DNSError.invalidServerAddress)
        #expect(DNSError.invalidDomainName != DNSError.parsingError(nil))
        #expect(DNSError.invalidDomainName != DNSError.parsingError(DNSError.noDataReceived))
    }
}

