//
//  TestDNSError.swift
//  SwiftDNS
//
//  Created by mtzfederico on 2025-08-20
// 

import Testing
@testable import SwiftDNS

struct TestDNSError {

    @Test func testDNSError_Equatable() async throws {
        #expect(DNSError.invalidData("") == DNSError.invalidData(""))
        #expect(DNSError.invalidData("") != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.invalidData("") != DNSError.unknownState(nil))
        #expect(DNSError.invalidData("") != DNSError.unknownState(.preparing))
        #expect(DNSError.invalidData("") != DNSError.noDataReceived)
        #expect(DNSError.invalidData("") != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.invalidData("") != DNSError.invalidDomainName)
        #expect(DNSError.invalidData("") != DNSError.connectionIsNil)
        #expect(DNSError.invalidData("") != DNSError.invalidServerAddress)
        #expect(DNSError.invalidData("") != DNSError.connectionFailed(DNSError.connectionIsNil))
        #expect(DNSError.invalidData("") != DNSError.parsingError(nil))
        #expect(DNSError.invalidData("") != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.invalidData("") != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.connectionIsNil != DNSError.invalidData(""))
        #expect(DNSError.connectionIsNil != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.connectionIsNil != DNSError.unknownState(nil))
        #expect(DNSError.connectionIsNil != DNSError.unknownState(.preparing))
        #expect(DNSError.connectionIsNil != DNSError.invalidServerAddress)
        #expect(DNSError.connectionIsNil != DNSError.noDataReceived)
        #expect(DNSError.connectionIsNil != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.connectionIsNil != DNSError.invalidDomainName)
        #expect(DNSError.connectionIsNil == DNSError.connectionIsNil)
        #expect(DNSError.connectionIsNil != DNSError.invalidServerAddress)
        #expect(DNSError.connectionIsNil != DNSError.connectionFailed(DNSError.invalidData("Out of bounds")))
        #expect(DNSError.connectionIsNil != DNSError.parsingError(nil))
        #expect(DNSError.connectionIsNil != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.connectionIsNil != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.invalidServerAddress != DNSError.invalidData(""))
        #expect(DNSError.invalidServerAddress != DNSError.unknownState(nil))
        #expect(DNSError.invalidServerAddress != DNSError.unknownState(.preparing))
        #expect(DNSError.invalidServerAddress != DNSError.noDataReceived)
        #expect(DNSError.invalidServerAddress != DNSError.noDataReceived)
        #expect(DNSError.invalidServerAddress != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.invalidServerAddress != DNSError.invalidDomainName)
        #expect(DNSError.invalidServerAddress != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.invalidServerAddress != DNSError.connectionIsNil)
        #expect(DNSError.invalidServerAddress == DNSError.invalidServerAddress)
        #expect(DNSError.invalidServerAddress != DNSError.connectionFailed(DNSError.noDataReceived))
        #expect(DNSError.invalidServerAddress != DNSError.parsingError(nil))
        #expect(DNSError.invalidServerAddress != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.invalidServerAddress != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.parsingError(nil) != DNSError.invalidData(""))
        #expect(DNSError.parsingError(nil) != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.parsingError(nil) != DNSError.unknownState(nil))
        #expect(DNSError.parsingError(nil) != DNSError.unknownState(.preparing))
        #expect(DNSError.parsingError(DNSError.invalidData("")) != DNSError.unknownState(.preparing))
        #expect(DNSError.parsingError(nil) != DNSError.invalidServerAddress)
        #expect(DNSError.parsingError(nil) != DNSError.noDataReceived)
        #expect(DNSError.parsingError(nil) != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.parsingError(nil) != DNSError.invalidDomainName)
        #expect(DNSError.parsingError(nil) != DNSError.connectionIsNil)
        #expect(DNSError.parsingError(nil) != DNSError.invalidServerAddress)
        #expect(DNSError.parsingError(nil) != DNSError.connectionFailed(DNSError.connectionIsNil))
        #expect(DNSError.parsingError(nil) == DNSError.parsingError(nil))
        #expect(DNSError.parsingError(DNSError.noDataReceived) == DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.parsingError(nil) != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.parsingError(nil) != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.unknownState(nil) != DNSError.invalidData(""))
        #expect(DNSError.unknownState(nil) != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.unknownState(nil) == DNSError.unknownState(nil))
        #expect(DNSError.unknownState(.preparing) == DNSError.unknownState(.preparing))
        #expect(DNSError.unknownState(nil) != DNSError.invalidServerAddress)
        #expect(DNSError.unknownState(nil) != DNSError.noDataReceived)
        #expect(DNSError.unknownState(nil) != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.unknownState(nil) != DNSError.invalidDomainName)
        #expect(DNSError.unknownState(nil) != DNSError.connectionIsNil)
        #expect(DNSError.unknownState(nil) != DNSError.invalidServerAddress)
        #expect(DNSError.unknownState(nil) != DNSError.connectionFailed(DNSError.connectionIsNil))
        #expect(DNSError.unknownState(nil) != DNSError.parsingError(nil))
        #expect(DNSError.unknownState(nil) != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.unknownState(nil) != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.invalidData(""))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.connectionFailed(DNSError.invalidData("Out of bounds")))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.unknownState(nil))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.unknownState(.preparing))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.noDataReceived)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.invalidDomainName)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.connectionIsNil)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.invalidServerAddress)
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) == DNSError.connectionFailed(DNSError.noDataReceived))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.parsingError(nil))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.connectionFailed(DNSError.noDataReceived) != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.noDataReceived != DNSError.invalidData(""))
        #expect(DNSError.noDataReceived != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.noDataReceived != DNSError.unknownState(nil))
        #expect(DNSError.noDataReceived != DNSError.unknownState(.preparing))
        #expect(DNSError.noDataReceived == DNSError.noDataReceived)
        #expect(DNSError.noDataReceived != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.noDataReceived != DNSError.invalidDomainName)
        #expect(DNSError.noDataReceived != DNSError.connectionIsNil)
        #expect(DNSError.noDataReceived != DNSError.invalidServerAddress)
        #expect(DNSError.noDataReceived != DNSError.parsingError(nil))
        #expect(DNSError.noDataReceived != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.noDataReceived != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.invalidData(""))
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.unknownState(nil))
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.unknownState(.preparing))
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.noDataReceived)
        #expect(DNSError.IDMismatch(got: 0, expected: 0) == DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.IDMismatch(got: 04323, expected: 12345) == DNSError.IDMismatch(got: 04323, expected: 12345))
        #expect(DNSError.IDMismatch(got: 0xab, expected: 0) == DNSError.IDMismatch(got: 0xab, expected: 0))
        #expect(DNSError.IDMismatch(got: 0, expected: 0xba) == DNSError.IDMismatch(got: 0, expected: 0xba))
        #expect(DNSError.IDMismatch(got: 0, expected: 0xbb) != DNSError.IDMismatch(got: 0, expected: 0xaa))
        #expect(DNSError.IDMismatch(got: 0xaa, expected: 0) != DNSError.IDMismatch(got: 0xbb, expected: 0))
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.invalidDomainName)
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.connectionIsNil)
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.invalidServerAddress)
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.parsingError(nil))
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.IDMismatch(got: 0, expected: 0) != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.invalidDomainName != DNSError.invalidData(""))
        #expect(DNSError.invalidDomainName != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.invalidDomainName != DNSError.unknownState(nil))
        #expect(DNSError.invalidDomainName != DNSError.unknownState(.preparing))
        #expect(DNSError.invalidDomainName != DNSError.noDataReceived)
        #expect(DNSError.invalidDomainName != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.invalidDomainName == DNSError.invalidDomainName)
        #expect(DNSError.invalidDomainName != DNSError.connectionIsNil)
        #expect(DNSError.invalidDomainName != DNSError.invalidServerAddress)
        #expect(DNSError.invalidDomainName != DNSError.parsingError(nil))
        #expect(DNSError.invalidDomainName != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.invalidDomainName != DNSError.connectionTypeMismatch)
        
        #expect(DNSError.connectionTypeMismatch != DNSError.invalidData(""))
        #expect(DNSError.connectionTypeMismatch != DNSError.invalidData("Out of bounds"))
        #expect(DNSError.connectionTypeMismatch != DNSError.unknownState(nil))
        #expect(DNSError.connectionTypeMismatch != DNSError.unknownState(.preparing))
        #expect(DNSError.connectionTypeMismatch != DNSError.noDataReceived)
        #expect(DNSError.connectionTypeMismatch != DNSError.IDMismatch(got: 0, expected: 0))
        #expect(DNSError.connectionTypeMismatch != DNSError.invalidDomainName)
        #expect(DNSError.connectionTypeMismatch != DNSError.connectionIsNil)
        #expect(DNSError.connectionTypeMismatch != DNSError.invalidServerAddress)
        #expect(DNSError.connectionTypeMismatch != DNSError.parsingError(nil))
        #expect(DNSError.connectionTypeMismatch != DNSError.parsingError(DNSError.noDataReceived))
        #expect(DNSError.connectionTypeMismatch == DNSError.connectionTypeMismatch)
    }
}

